# Generated by Django 3.1.2 on 2020-10-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_image',
            field=models.ImageField(default='default.jpg', upload_to='plant_pics'),
        ),
    ]
